version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 505076619770.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - docker build -t cicd-demo .
      - docker tag cicd-demo:latest 851725608112.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-demo:latest
  post_build:
    commands:
      - docker push 851725608112.dkr.ecr.ap-southeast-1.amazonaws.com/cicd-demo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"mywebsite","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json   
artifacts:
  files: imagedefinitions.json